sensu-plugins/sensu-plugins-network-checks

bin/metrics-sockstat.rb, sensu-plugins-network-checks.gemspec, test/metrics-sockstat_spec.rb, test/plugin_stub.rb
This adds a metric check that parses /proc/net/sockstat on Linux systems and outputs all fields as metrics. Tests are included.
=> Sockstat metrics

bin/check-banner.rb
* Added support for multiple host pattern matching, with success based on the
number of matches. This can be used for example to check that a Zookeeper
ensemble has a single leader.
* Option to read banner till a custom character is reached, for example read
till EOF or EOL.
* Options to override ok and critical message.
* The default behaviour remains unchanged
=> Multiple hosts supported with additional matching options

CHANGELOG.md, bin/check-ports.rb
Support multiple port ranges
```
$ ./check-ports.rb -H localhost -p 8103,8110-8120,8104 -t 30
CheckPort OK: All ports (8103,8110-8120,8104) are accessible for host localhost
```
=> check-ports: support port ranges

CHANGELOG.md, bin/metrics-net.rb
Devices now can be specifically included or ignored using `-i` or `-I` options
=> Added include and ignore options for devices

CHANGELOG.md, lib/sensu-plugins-network-checks/version.rb, sensu-plugins-network-checks.gemspec
adding runtime dep for activesupport 4.2.5 to ensure that you do not need ruby >= 2.2
```
STDERR: ERROR:  Error installing sensu-plugins-network-checks:
activesupport requires Ruby version >= 2.2.2.
---- End output of /opt/rbenv/shims/gem install sensu-plugins-network-checks -q --no-rdoc --no-ri -v "0.0.2" ----
Ran /opt/rbenv/shims/gem install sensu-plugins-network-checks -q --no-rdoc --no-ri -v "0.0.2" returned 1
Resource Declaration:
---------------------
89: gem_package 'sensu-plugins-network-checks' do
90:   version '0.0.2'
91: end
92: 
Compiled Resource:
------------------
gem_package("sensu-plugins-network-checks") do
action [:install]
retries 0
retry_delay 2
default_guard_interpreter :default
package_name "sensu-plugins-network-checks"
version "0.0.2"
declared_type :gem_package …
```
=> lock activesupport gem

CHANGELOG.md, bin/check-jsonwhois-domain-expiration.rb, bin/check-whois-domain-expiration-multi.rb
Fixes a bug in `check-whois-domain-expiration-multi` where the check would fail to exit if there were any domains with expiration dates in the `warning` time period but none in the `critical` time period.
The bug was copied to `check-jsonwhois-domain-expiration` at creation.
=> bugfix: return warning if there are items in the warning hash

CHANGELOG.md, bin/check-socat.rb
I intended to use this to check if the machine can receive UDP multicast packets. There might be other useful cases as `socat` could do a lot of things.
=> Add check-socat.rb

CHANGELOG.md, bin/check-ping.rb, sensu-plugins-network-checks.gemspec
I added ipv6 support for check-ping. Unfortunately there were no unit tests for check-ping at all to add ipv6 test cases :-(
=> Add ipv6 support for check-ping

bin/metrics-ping.rb
`ping` result:
```
rrt min/avg/max/mdev = 14.465/21.527/28.589/7.062 ms
```
The order is `min`,`avg`,`max`,`mdev`
=> fixed metrics-ping statistic order

bin/metrics-ping.rb
This PR adds warning as requested in #26 
Btw: I'm not a Ruby developer so I haven't tested if this script is still working. It should since I only added a comment.
=> metrics-ping.rb: added a warning about different 'ping' versions

CHANGELOG.md, bin/check-whois-domain-expiration-multi.rb
Add `timeout` option and increase to 10 seconds - whois gem defaults to 5 seconds, which is too short for some whois servers. Also retry connection errors.
Before: 
```
/opt/sensu/embedded/bin/check-whois-domain-expiration-multi.rb -d ... -w 30 -c 7
Check failed to run: Errno::ECONNRESET: Connection reset by peer, ["/opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/whois-3.6.3/lib/whois/server/socket_handler.rb:40:in `rescue in call'", "/opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/whois-3.6.3/lib/whois/server/socket_handler.rb:38:in `call'", "/opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/whois-3.6.3/lib/whois/server/adapters/base.rb:175:in `query'", "/opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/whois-3.6.3/lib/whois/server/adapters/verisign.rb:33:in `request'", …
```
=> Handle whois errors better

bin/check-banner.rb, bin/check-ports.rb
From ruby 2.3.0, use of Object#timeout prints a deprecation warning:
Object#timeout is deprecated, use Timeout.timeout instead
=> Use Timeout.timeout not deprecated Object#timeout.

CHANGELOG.md, bin/metrics-netstat-tcp.rb
Adding an option to disable the tcp6 check.  On nodes where tcp6 is disabled, this metric check throws errors because...
Check failed to run: No such file or directory @ rb_sysopen - /proc/net/tcp6
=> Metrics netstat tcp disable tcp6

CHANGELOG.md, bin/check-banner.rb
This is useful when checking for banner and connection is secure (SSL/TLS).
A good example would be FTPS.
Requires 'openssl'
=> check-banner.rb: Option to enable SSL socket for secure connection

CHANGELOG.md, bin/check-multicast-groups.rb
**Is this in reference to an existing issue?**
No, it fixes a new issue.
`sensu-plugin` has stopped monkey patching `Array` with `deep_merge`. This causes `check-multicast-groups` to fail:
```
% /opt/sensu/embedded/bin/ruby ./bin/check-multicast-groups.rb -c network.json
CheckMulticastGroups CRITICAL: Failed to check multicast groups: undefined method `deep_merge' for []:Array
```
This PR is a fix for this with minor corrections.
I'm not aware of any compatibility issues. I believe the new code is also compatible with older `sensu-plugin`.
=> Fix undefined method deep_merge in check-multicast-groups.rb

CHANGELOG.md, bin/metrics-netif.rb
Add the option to collect interface metrics over a longer period of time for a better average, Useful for those of us using a TSDB (i.e. Graphite) with precision set to minutely -- Collecting over 30 seconds would give a better general average than a 1 second collection.
None - Default value matches that of existing check
=> Added interval option to metrics-netif.rb

CHANGELOG.md, bin/metrics-netif.rb
This is important for supporting multiple locales.
#46 
Grepping and parsing is often an issue with different locales, expose some of these options so that the user can configure them to work for their locale.
none that I am aware of.
=> closes #46 by exposing option that is used to grep.

CHANGELOG.md, bin/check-multicast-groups.rb
**Is this in reference to an existing issue?** No.
Loading targets from `settings['check-multicast-groups']` can be inconvenient if the user want to put multiple configs in the sensu config path as it merges all the available targets. This patch stops the plugin from loading `settings['check-multicast-groups']` and have it use only the specified config.
This is technically a breaking change but I expected the impact to be negligible because it makes no sense to run multiple checks that have the same targets in the system settings. So I think all the users must not be using the system settings.
=> Stop using settings['check-multicast-groups']

CHANGELOG.md, bin/check-whois-domain-expiration-multi.rb, bin/check-whois-domain-expiration.rb, sensu-plugins-network-checks.gemspec
This pull request is in response to #59 
To add the new whois-parser gem for use with the whois domain expiration checks.
N/A
=> Add whois-parser to check-whois-domain-expiration.rb

CHANGELOG.md, bin/metrics-interface.rb
Till now we just had exclude interface option, nothing to just select specific interface.
**Is this in reference to an existing issue?**
=> Adds include interface option

CHANGELOG.md, bin/check-whois-domain-expiration-multi.rb
The code before didn't throw an error for empty expires_on. This would mean if the whois-parser gem is failing to return a result you could have a false negative. The solution is to throw an error and force a fix to get a proper answer.
I was having this issue with the TLDs .co and .us. I separately made pull requests to fix them with whois-parser.
=> Fix check-whois-domain-expiration-multi.rb to report a critical error on a domain that it gets back an empty expires_on.

CHANGELOG.md, sensu-plugins-network-checks.gemspec
Fixes #73.
Fixes #73 by bumping the `whois-parser` gem to version 1.0.1 (https://github.com/weppos/whois-parser/blob/master/CHANGELOG.md).
N/A
=> Update whois-parser gem to 1.0.1.
